export const sampleRawDeals = [
  {
    source_name: 'Maricopa Probate Feed',
    source_type: 'probate',
    source_id: 'MP-001',
    title: 'Off-market probate single family opportunity',
    city: 'Phoenix',
    state: 'AZ',
    address: 'North Phoenix Area',
    zip_code: '85021',
    property_type: 'Single Family',
    estimated_value: 395000,
    purchase_price: 278000,
    description:
      'Probate-linked single family property with strong discount and motivated disposition pressure.',
    notes: 'Owner situation suggests flexible negotiation.',
    signal: 'probate motivated seller off-market',
    contact_name: '',
    contact_phone: '',
    contact_email: '',
    status: 'opportunity',
  },
  {
    source_name: 'Tucson Distress Monitor',
    source_type: 'distress',
    source_id: 'TD-002',
    title: 'Vacant duplex with repricing weakness',
    city: 'Tucson',
    state: 'AZ',
    address: 'Central Tucson',
    zip_code: '85705',
    property_type: 'Duplex',
    estimated_value: 310000,
    purchase_price: 232000,
    description:
      'Vacant duplex opportunity with visible distress indicators and potential repositioning upside.',
    notes: 'Needs cosmetic work. Tenant instability reported.',
    signal: 'vacant distressed fixer',
    contact_name: '',
    contact_phone: '',
    contact_email: '',
    status: 'opportunity',
  },
  {
    source_name: 'Arizona Open Feed',
    source_type: 'public',
    source_id: 'AZ-003',
    title: 'Standard residential opportunity',
    city: 'Mesa',
    state: 'AZ',
    address: 'East Mesa',
    zip_code: '85204',
    property_type: 'Single Family',
    estimated_value: 340000,
    purchase_price: 301000,
    description:
      'Lower-discount residential deal with moderate upside and decent market positioning.',
    notes: 'Clean record, lower urgency.',
    signal: 'standard listing',
    contact_name: '',
    contact_phone: '',
    contact_email: '',
    status: 'opportunity',
  },
  {
    source_name: 'Investor Lead Sheet',
    source_type: 'manual',
    source_id: 'IL-004',
    title: 'Pre-foreclosure multifamily lead',
    city: 'Scottsdale',
    state: 'AZ',
    address: 'South Scottsdale',
    zip_code: '85257',
    property_type: 'Multi Family',
    estimated_value: 890000,
    purchase_price: 590000,
    description:
      'Pre-foreclosure multifamily deal with strong spread and high investor relevance.',
    notes: 'Needs fast review. Seller pressure increasing.',
    signal: 'pre-foreclosure off-market distressed',
    contact_name: '',
    contact_phone: '',
    contact_email: '',
    status: 'opportunity',
  },
]