export { LEGAL_PAGES, LEGAL_PAGE_LIST, getLegalPage, resolveLegalPage } from './legalPages'
export { default as LegalDocumentLayout } from './LegalDocumentLayout'
export { default as LegalDocumentPage } from './LegalDocumentPage'
export { default as LegalRouter } from './LegalRouter'

export { default as TermsOfServicePage } from './pages/TermsOfServicePage'
export { default as PrivacyPolicyPage } from './pages/PrivacyPolicyPage'
export { default as CookiePolicyPage } from './pages/CookiePolicyPage'
export { default as InvestmentDisclaimerPage } from './pages/InvestmentDisclaimerPage'
export { default as SubscriptionTermsPage } from './pages/SubscriptionTermsPage'
export { default as PremiumPurchaseTermsPage } from './pages/PremiumPurchaseTermsPage'
export { default as DiamondPurchaseTermsPage } from './pages/DiamondPurchaseTermsPage'
export { default as OwnerAgreementPage } from './pages/OwnerAgreementPage'
export { default as AcceptableUsePolicyPage } from './pages/AcceptableUsePolicyPage'
export { default as LegalNoticePage } from './pages/LegalNoticePage'
export { default as DiamondAuthorizationAgreementPage } from './pages/DiamondAuthorizationAgreementPage'
export { default as FounderProgramTermsPage } from './pages/FounderProgramTermsPage'
export { default as MarketplaceRulesPage } from './pages/MarketplaceRulesPage'
export { default as RefundPolicyPage } from './pages/RefundPolicyPage'
export { default as DataRetentionPolicyPage } from './pages/DataRetentionPolicyPage'
export { default as AiAutomationDisclosurePage } from './pages/AiAutomationDisclosurePage'
export { default as LegalDefinitionsPage } from './pages/LegalDefinitionsPage'
export { default as LegalIndexPage } from './pages/LegalIndexPage'
